### ISSUE TITLE
Error: Cannot find module 'estree-walker'

### ISSUE THREAD

**Issue by brielov** [Dohxis/rollup-plugin-tailwind#1]
I've just created a new rollup project and when I try to build this is what I get.

```
[!] Error: Cannot find module 'estree-walker'
Require stack:
- /Users/brielov/Code/@cuitapp/website/node_modules/rollup-plugin-tailwind/dist-node/index.js
- /Users/brielov/Code/@cuitapp/website/rollup.config.js
- /Users/brielov/Code/@cuitapp/website/node_modules/rollup/dist/bin/rollup
Error: Cannot find module 'estree-walker'
Require stack:
- /Users/brielov/Code/@cuitapp/website/node_modules/rollup-plugin-tailwind/dist-node/index.js
- /Users/brielov/Code/@cuitapp/website/rollup.config.js
- /Users/brielov/Code/@cuitapp/website/node_modules/rollup/dist/bin/rollup
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/brielov/Code/@cuitapp/website/node_modules/rollup-plugin-tailwind/dist-node/index.js:8:20)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Object.require.extensions..js (/Users/brielov/Code/@cuitapp/website/node_modules/rollup/dist/bin/rollup:841:17)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
```

And this is my rollup.config.js

```javascript
import tailwind from 'rollup-plugin-tailwind';

export default {
  input: 'src/index.js',
  output: {
    file: 'build/bundle.js',
    format: 'cjs',
  },
  plugins: [tailwind({ config: 'tailwind.js' })],
};
```

Am I missing something?

**Comment by Dohxis** [comment]
Thanks for the issue. Your configuration seems right so that it could be something with the bundler. I will take a look.
